### ISSUE TITLE
psycopg3 was released, is there a plan to put it on a feedstock?

### ISSUE THREAD

**Issue by mattip** [conda-forge/psycopg2-feedstock#53]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
I don't know where the correct place to ask is. Psycopg3 [was released](https://www.psycopg.org/articles/2021/10/13/psycopg-30-released/) in October 2021. Is the plan to update this feedstock to 3 or to open a new one in parallel with this one?

**Comment by xylar** [comment]
Thanks for bringing this to our attention @mattip.  When a similar change happened with proj, we kept the [proj.4-feedstock](https://github.com/conda-forge/proj.4-feedstock) but renamed the package produced to `proj`, so I would think we would do the same here.  I will make a PR, starting from 3.0.

**Comment by xylar** [comment]
Update: this looks a bit complicated, since there are actually 3 packages here: `psycopg`, `psycopg-binary` and `psycopg-c`.  I'll need to test some local builds and determine if these should each be their own feedstocks or if they can all live here.  I probably won't get to this for at least a few days, so if someone else has time to give this a go, just let me know.

**Comment by xylar** [comment]
@mattip, I think I finally have this handled in #54.  Please have a look if you have time.

**Comment by mattip** [comment]
Cool, the 3.0.9 release automatically updated.

**Comment by xylar** [comment]
Semi-automatically with a little help from me ;-)

**Comment by mattip** [comment]
Even cooler, since upstream released less than 24 hours ago. Thanks!
